package com.kaerushi.monetify.core.ui.theme.color

import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val BluePrimaryLight = Color(0xFF415F91)
val BlueOnPrimaryLight = Color(0xFFFFFFFF)
val BluePrimaryContainerLight = Color(0xFFD6E3FF)
val BlueOnPrimaryContainerLight = Color(0xFF284777)
val BlueSecondaryLight = Color(0xFF565F71)
val BlueOnSecondaryLight = Color(0xFFFFFFFF)
val BlueSecondaryContainerLight = Color(0xFFDAE2F9)
val BlueOnSecondaryContainerLight = Color(0xFF3E4759)
val BlueTertiaryLight = Color(0xFF705575)
val BlueOnTertiaryLight = Color(0xFFFFFFFF)
val BlueTertiaryContainerLight = Color(0xFFFAD8FD)
val BlueOnTertiaryContainerLight = Color(0xFF573E5C)
val BlueErrorLight = Color(0xFFBA1A1A)
val BlueOnErrorLight = Color(0xFFFFFFFF)
val BlueErrorContainerLight = Color(0xFFFFDAD6)
val BlueOnErrorContainerLight = Color(0xFF93000A)
val BlueBackgroundLight = Color(0xFFF9F9FF)
val BlueOnBackgroundLight = Color(0xFF191C20)
val BlueSurfaceLight = Color(0xFFF9F9FF)
val BlueOnSurfaceLight = Color(0xFF191C20)
val BlueSurfaceVariantLight = Color(0xFFE0E2EC)
val BlueOnSurfaceVariantLight = Color(0xFF44474E)
val BlueOutlineLight = Color(0xFF74777F)
val BlueOutlineVariantLight = Color(0xFFC4C6D0)
val BlueScrimLight = Color(0xFF000000)
val BlueInverseSurfaceLight = Color(0xFF2E3036)
val BlueInverseOnSurfaceLight = Color(0xFFF0F0F7)
val BlueInversePrimaryLight = Color(0xFFAAC7FF)
val BlueSurfaceDimLight = Color(0xFFD9D9E0)
val BlueSurfaceBrightLight = Color(0xFFF9F9FF)
val BlueSurfaceContainerLowestLight = Color(0xFFFFFFFF)
val BlueSurfaceContainerLowLight = Color(0xFFF3F3FA)
val BlueSurfaceContainerLight = Color(0xFFEDEDF4)
val BlueSurfaceContainerHighLight = Color(0xFFE7E8EE)
val BlueSurfaceContainerHighestLight = Color(0xFFE2E2E9)

val BluePrimaryLightMediumContrast = Color(0xFF133665)
val BlueOnPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val BluePrimaryContainerLightMediumContrast = Color(0xFF506DA0)
val BlueOnPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val BlueSecondaryLightMediumContrast = Color(0xFF2E3647)
val BlueOnSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val BlueSecondaryContainerLightMediumContrast = Color(0xFF646D80)
val BlueOnSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val BlueTertiaryLightMediumContrast = Color(0xFF452E4A)
val BlueOnTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val BlueTertiaryContainerLightMediumContrast = Color(0xFF7F6484)
val BlueOnTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val BlueErrorLightMediumContrast = Color(0xFF740006)
val BlueOnErrorLightMediumContrast = Color(0xFFFFFFFF)
val BlueErrorContainerLightMediumContrast = Color(0xFFCF2C27)
val BlueOnErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val BlueBackgroundLightMediumContrast = Color(0xFFF9F9FF)
val BlueOnBackgroundLightMediumContrast = Color(0xFF191C20)
val BlueSurfaceLightMediumContrast = Color(0xFFF9F9FF)
val BlueOnSurfaceLightMediumContrast = Color(0xFF0F1116)
val BlueSurfaceVariantLightMediumContrast = Color(0xFFE0E2EC)
val BlueOnSurfaceVariantLightMediumContrast = Color(0xFF33363E)
val BlueOutlineLightMediumContrast = Color(0xFF4F525A)
val BlueOutlineVariantLightMediumContrast = Color(0xFF6A6D75)
val BlueScrimLightMediumContrast = Color(0xFF000000)
val BlueInverseSurfaceLightMediumContrast = Color(0xFF2E3036)
val BlueInverseOnSurfaceLightMediumContrast = Color(0xFFF0F0F7)
val BlueInversePrimaryLightMediumContrast = Color(0xFFAAC7FF)
val BlueSurfaceDimLightMediumContrast = Color(0xFFC5C6CD)
val BlueSurfaceBrightLightMediumContrast = Color(0xFFF9F9FF)
val BlueSurfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val BlueSurfaceContainerLowLightMediumContrast = Color(0xFFF3F3FA)
val BlueSurfaceContainerLightMediumContrast = Color(0xFFE7E8EE)
val BlueSurfaceContainerHighLightMediumContrast = Color(0xFFDCDCE3)
val BlueSurfaceContainerHighestLightMediumContrast = Color(0xFFD1D1D8)

val BluePrimaryLightHighContrast = Color(0xFF032B5B)
val BlueOnPrimaryLightHighContrast = Color(0xFFFFFFFF)
val BluePrimaryContainerLightHighContrast = Color(0xFF2A497A)
val BlueOnPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val BlueSecondaryLightHighContrast = Color(0xFF232C3D)
val BlueOnSecondaryLightHighContrast = Color(0xFFFFFFFF)
val BlueSecondaryContainerLightHighContrast = Color(0xFF41495B)
val BlueOnSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val BlueTertiaryLightHighContrast = Color(0xFF3A2440)
val BlueOnTertiaryLightHighContrast = Color(0xFFFFFFFF)
val BlueTertiaryContainerLightHighContrast = Color(0xFF59405E)
val BlueOnTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val BlueErrorLightHighContrast = Color(0xFF600004)
val BlueOnErrorLightHighContrast = Color(0xFFFFFFFF)
val BlueErrorContainerLightHighContrast = Color(0xFF98000A)
val BlueOnErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val BlueBackgroundLightHighContrast = Color(0xFFF9F9FF)
val BlueOnBackgroundLightHighContrast = Color(0xFF191C20)
val BlueSurfaceLightHighContrast = Color(0xFFF9F9FF)
val BlueOnSurfaceLightHighContrast = Color(0xFF000000)
val BlueSurfaceVariantLightHighContrast = Color(0xFFE0E2EC)
val BlueOnSurfaceVariantLightHighContrast = Color(0xFF000000)
val BlueOutlineLightHighContrast = Color(0xFF292C33)
val BlueOutlineVariantLightHighContrast = Color(0xFF464951)
val BlueScrimLightHighContrast = Color(0xFF000000)
val BlueInverseSurfaceLightHighContrast = Color(0xFF2E3036)
val BlueInverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val BlueInversePrimaryLightHighContrast = Color(0xFFAAC7FF)
val BlueSurfaceDimLightHighContrast = Color(0xFFB8B8BF)
val BlueSurfaceBrightLightHighContrast = Color(0xFFF9F9FF)
val BlueSurfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val BlueSurfaceContainerLowLightHighContrast = Color(0xFFF0F0F7)
val BlueSurfaceContainerLightHighContrast = Color(0xFFE2E2E9)
val BlueSurfaceContainerHighLightHighContrast = Color(0xFFD3D4DB)
val BlueSurfaceContainerHighestLightHighContrast = Color(0xFFC5C6CD)

val BluePrimaryDark = Color(0xFFAAC7FF)
val BlueOnPrimaryDark = Color(0xFF0A305F)
val BluePrimaryContainerDark = Color(0xFF284777)
val BlueOnPrimaryContainerDark = Color(0xFFD6E3FF)
val BlueSecondaryDark = Color(0xFFBEC6DC)
val BlueOnSecondaryDark = Color(0xFF283141)
val BlueSecondaryContainerDark = Color(0xFF3E4759)
val BlueOnSecondaryContainerDark = Color(0xFFDAE2F9)
val BlueTertiaryDark = Color(0xFFDDBCE0)
val BlueOnTertiaryDark = Color(0xFF3F2844)
val BlueTertiaryContainerDark = Color(0xFF573E5C)
val BlueOnTertiaryContainerDark = Color(0xFFFAD8FD)
val BlueErrorDark = Color(0xFFFFB4AB)
val BlueOnErrorDark = Color(0xFF690005)
val BlueErrorContainerDark = Color(0xFF93000A)
val BlueOnErrorContainerDark = Color(0xFFFFDAD6)
val BlueBackgroundDark = Color(0xFF111318)
val BlueOnBackgroundDark = Color(0xFFE2E2E9)
val BlueSurfaceDark = Color(0xFF111318)
val BlueOnSurfaceDark = Color(0xFFE2E2E9)
val BlueSurfaceVariantDark = Color(0xFF44474E)
val BlueOnSurfaceVariantDark = Color(0xFFC4C6D0)
val BlueOutlineDark = Color(0xFF8E9099)
val BlueOutlineVariantDark = Color(0xFF44474E)
val BlueScrimDark = Color(0xFF000000)
val BlueInverseSurfaceDark = Color(0xFFE2E2E9)
val BlueInverseOnSurfaceDark = Color(0xFF2E3036)
val BlueInversePrimaryDark = Color(0xFF415F91)
val BlueSurfaceDimDark = Color(0xFF111318)
val BlueSurfaceBrightDark = Color(0xFF37393E)
val BlueSurfaceContainerLowestDark = Color(0xFF0C0E13)
val BlueSurfaceContainerLowDark = Color(0xFF191C20)
val BlueSurfaceContainerDark = Color(0xFF1D2024)
val BlueSurfaceContainerHighDark = Color(0xFF282A2F)
val BlueSurfaceContainerHighestDark = Color(0xFF33353A)

val BluePrimaryDarkMediumContrast = Color(0xFFCDDDFF)
val BlueOnPrimaryDarkMediumContrast = Color(0xFF002551)
val BluePrimaryContainerDarkMediumContrast = Color(0xFF7491C7)
val BlueOnPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val BlueSecondaryDarkMediumContrast = Color(0xFFD4DCF2)
val BlueOnSecondaryDarkMediumContrast = Color(0xFF1D2636)
val BlueSecondaryContainerDarkMediumContrast = Color(0xFF8891A5)
val BlueOnSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val BlueTertiaryDarkMediumContrast = Color(0xFFF3D2F7)
val BlueOnTertiaryDarkMediumContrast = Color(0xFF331D39)
val BlueTertiaryContainerDarkMediumContrast = Color(0xFFA487A9)
val BlueOnTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val BlueErrorDarkMediumContrast = Color(0xFFFFD2CC)
val BlueOnErrorDarkMediumContrast = Color(0xFF540003)
val BlueErrorContainerDarkMediumContrast = Color(0xFFFF5449)
val BlueOnErrorContainerDarkMediumContrast = Color(0xFF000000)
val BlueBackgroundDarkMediumContrast = Color(0xFF111318)
val BlueOnBackgroundDarkMediumContrast = Color(0xFFE2E2E9)
val BlueSurfaceDarkMediumContrast = Color(0xFF111318)
val BlueOnSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val BlueSurfaceVariantDarkMediumContrast = Color(0xFF44474E)
val BlueOnSurfaceVariantDarkMediumContrast = Color(0xFFDADCE6)
val BlueOutlineDarkMediumContrast = Color(0xFFAFB2BB)
val BlueOutlineVariantDarkMediumContrast = Color(0xFF8E9099)
val BlueScrimDarkMediumContrast = Color(0xFF000000)
val BlueInverseSurfaceDarkMediumContrast = Color(0xFFE2E2E9)
val BlueInverseOnSurfaceDarkMediumContrast = Color(0xFF282A2F)
val BlueInversePrimaryDarkMediumContrast = Color(0xFF294878)
val BlueSurfaceDimDarkMediumContrast = Color(0xFF111318)
val BlueSurfaceBrightDarkMediumContrast = Color(0xFF43444A)
val BlueSurfaceContainerLowestDarkMediumContrast = Color(0xFF06070C)
val BlueSurfaceContainerLowDarkMediumContrast = Color(0xFF1B1E22)
val BlueSurfaceContainerDarkMediumContrast = Color(0xFF26282D)
val BlueSurfaceContainerHighDarkMediumContrast = Color(0xFF313238)
val BlueSurfaceContainerHighestDarkMediumContrast = Color(0xFF3C3E43)

val BluePrimaryDarkHighContrast = Color(0xFFEBF0FF)
val BlueOnPrimaryDarkHighContrast = Color(0xFF000000)
val BluePrimaryContainerDarkHighContrast = Color(0xFFA6C3FC)
val BlueOnPrimaryContainerDarkHighContrast = Color(0xFF000B20)
val BlueSecondaryDarkHighContrast = Color(0xFFEBF0FF)
val BlueOnSecondaryDarkHighContrast = Color(0xFF000000)
val BlueSecondaryContainerDarkHighContrast = Color(0xFFBAC3D8)
val BlueOnSecondaryContainerDarkHighContrast = Color(0xFF030B1A)
val BlueTertiaryDarkHighContrast = Color(0xFFFFE9FF)
val BlueOnTertiaryDarkHighContrast = Color(0xFF000000)
val BlueTertiaryContainerDarkHighContrast = Color(0xFFD8B8DC)
val BlueOnTertiaryContainerDarkHighContrast = Color(0xFF16041D)
val BlueErrorDarkHighContrast = Color(0xFFFFECE9)
val BlueOnErrorDarkHighContrast = Color(0xFF000000)
val BlueErrorContainerDarkHighContrast = Color(0xFFFFAEA4)
val BlueOnErrorContainerDarkHighContrast = Color(0xFF220001)
val BlueBackgroundDarkHighContrast = Color(0xFF111318)
val BlueOnBackgroundDarkHighContrast = Color(0xFFE2E2E9)
val BlueSurfaceDarkHighContrast = Color(0xFF111318)
val BlueOnSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val BlueSurfaceVariantDarkHighContrast = Color(0xFF44474E)
val BlueOnSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val BlueOutlineDarkHighContrast = Color(0xFFEEEFF9)
val BlueOutlineVariantDarkHighContrast = Color(0xFFC0C2CC)
val BlueScrimDarkHighContrast = Color(0xFF000000)
val BlueInverseSurfaceDarkHighContrast = Color(0xFFE2E2E9)
val BlueInverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val BlueInversePrimaryDarkHighContrast = Color(0xFF294878)
val BlueSurfaceDimDarkHighContrast = Color(0xFF111318)
val BlueSurfaceBrightDarkHighContrast = Color(0xFF4E5056)
val BlueSurfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val BlueSurfaceContainerLowDarkHighContrast = Color(0xFF1D2024)
val BlueSurfaceContainerDarkHighContrast = Color(0xFF2E3036)
val BlueSurfaceContainerHighDarkHighContrast = Color(0xFF393B41)
val BlueSurfaceContainerHighestDarkHighContrast = Color(0xFF45474C)

val BlueLightColorScheme = lightColorScheme(
    primary = BluePrimaryLight,
    onPrimary = BlueOnPrimaryLight,
    primaryContainer = BluePrimaryContainerLight,
    onPrimaryContainer = BlueOnPrimaryContainerLight,
    inversePrimary = BlueInversePrimaryLight,
    secondary = BlueSecondaryLight,
    onSecondary = BlueOnSecondaryLight,
    secondaryContainer = BlueSecondaryContainerLight,
    onSecondaryContainer = BlueOnSecondaryContainerLight,
    tertiary = BlueTertiaryLight,
    onTertiary = BlueOnTertiaryLight,
    tertiaryContainer = BlueTertiaryContainerLight,
    onTertiaryContainer = BlueOnTertiaryContainerLight,
    background = BlueBackgroundLight,
    onBackground = BlueOnBackgroundLight,
    surface = BlueSurfaceLight,
    onSurface = BlueOnSurfaceLight,
    surfaceVariant = BlueSurfaceVariantLight,
    onSurfaceVariant = BlueOnSurfaceVariantLight,
    surfaceTint = BluePrimaryLight,
    inverseSurface = BlueInverseSurfaceLight,
    inverseOnSurface = BlueInverseOnSurfaceLight,
    error = BlueErrorLight,
    onError = BlueOnErrorLight,
    errorContainer = BlueErrorContainerLight,
    onErrorContainer = BlueOnErrorContainerLight,
    outline = BlueOutlineLight,
    outlineVariant = BlueOutlineVariantLight,
    scrim = BlueScrimLight,
    surfaceBright = BlueSurfaceBrightLight,
    surfaceContainer = BlueSurfaceContainerLight,
    surfaceContainerHigh = BlueSurfaceContainerHighLight,
    surfaceContainerHighest = BlueSurfaceContainerHighestLight,
    surfaceContainerLow = BlueSurfaceContainerLowLight,
    surfaceContainerLowest = BlueSurfaceContainerLowestLight,
    surfaceDim = BlueSurfaceDimLight
)

val BlueDarkColorScheme = lightColorScheme(
    primary = BluePrimaryDark,
    onPrimary = BlueOnPrimaryDark,
    primaryContainer = BluePrimaryContainerDark,
    onPrimaryContainer = BlueOnPrimaryContainerDark,
    inversePrimary = BlueInversePrimaryDark,
    secondary = BlueSecondaryDark,
    onSecondary = BlueOnSecondaryDark,
    secondaryContainer = BlueSecondaryContainerDark,
    onSecondaryContainer = BlueOnSecondaryContainerDark,
    tertiary = BlueTertiaryDark,
    onTertiary = BlueOnTertiaryDark,
    tertiaryContainer = BlueTertiaryContainerDark,
    onTertiaryContainer = BlueOnTertiaryContainerDark,
    background = BlueBackgroundDark,
    onBackground = BlueOnBackgroundDark,
    surface = BlueSurfaceDark,
    onSurface = BlueOnSurfaceDark,
    surfaceVariant = BlueSurfaceVariantDark,
    onSurfaceVariant = BlueOnSurfaceVariantDark,
    surfaceTint = BluePrimaryDark,
    inverseSurface = BlueInverseSurfaceDark,
    inverseOnSurface = BlueInverseOnSurfaceDark,
    error = BlueErrorDark,
    onError = BlueOnErrorDark,
    errorContainer = BlueErrorContainerDark,
    onErrorContainer = BlueOnErrorContainerDark,
    outline = BlueOutlineDark,
    outlineVariant = BlueOutlineVariantDark,
    scrim = BlueScrimDark,
    surfaceBright = BlueSurfaceBrightDark,
    surfaceContainer = BlueSurfaceContainerDark,
    surfaceContainerHigh = BlueSurfaceContainerHighDark,
    surfaceContainerHighest = BlueSurfaceContainerHighestDark,
    surfaceContainerLow = BlueSurfaceContainerLowDark,
    surfaceContainerLowest = BlueSurfaceContainerLowestDark,
    surfaceDim = BlueSurfaceDimDark
)