package com.kaerushi.monetify.core.ui.theme.color

import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val GreenPrimaryLight = Color(0xFF4C662B)
val GreenOnPrimaryLight = Color(0xFFFFFFFF)
val GreenPrimaryContainerLight = Color(0xFFCDEDA3)
val GreenOnPrimaryContainerLight = Color(0xFF354E16)
val GreenSecondaryLight = Color(0xFF586249)
val GreenOnSecondaryLight = Color(0xFFFFFFFF)
val GreenSecondaryContainerLight = Color(0xFFDCE7C8)
val GreenOnSecondaryContainerLight = Color(0xFF404A33)
val GreenTertiaryLight = Color(0xFF386663)
val GreenOnTertiaryLight = Color(0xFFFFFFFF)
val GreenTertiaryContainerLight = Color(0xFFBCECE7)
val GreenOnTertiaryContainerLight = Color(0xFF1F4E4B)
val GreenErrorLight = Color(0xFFBA1A1A)
val GreenOnErrorLight = Color(0xFFFFFFFF)
val GreenErrorContainerLight = Color(0xFFFFDAD6)
val GreenOnErrorContainerLight = Color(0xFF93000A)
val GreenBackgroundLight = Color(0xFFF9FAEF)
val GreenOnBackgroundLight = Color(0xFF1A1C16)
val GreenSurfaceLight = Color(0xFFF9FAEF)
val GreenOnSurfaceLight = Color(0xFF1A1C16)
val GreenSurfaceVariantLight = Color(0xFFE1E4D5)
val GreenOnSurfaceVariantLight = Color(0xFF44483D)
val GreenOutlineLight = Color(0xFF75796C)
val GreenOutlineVariantLight = Color(0xFFC5C8BA)
val GreenScrimLight = Color(0xFF000000)
val GreenInverseSurfaceLight = Color(0xFF2F312A)
val GreenInverseOnSurfaceLight = Color(0xFFF1F2E6)
val GreenInversePrimaryLight = Color(0xFFB1D18A)
val GreenSurfaceDimLight = Color(0xFFDADBD0)
val GreenSurfaceBrightLight = Color(0xFFF9FAEF)
val GreenSurfaceContainerLowestLight = Color(0xFFFFFFFF)
val GreenSurfaceContainerLowLight = Color(0xFFF3F4E9)
val GreenSurfaceContainerLight = Color(0xFFEEEFE3)
val GreenSurfaceContainerHighLight = Color(0xFFE8E9DE)
val GreenSurfaceContainerHighestLight = Color(0xFFE2E3D8)

val GreenPrimaryLightMediumContrast = Color(0xFF253D05)
val GreenOnPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val GreenPrimaryContainerLightMediumContrast = Color(0xFF5A7539)
val GreenOnPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val GreenSecondaryLightMediumContrast = Color(0xFF303924)
val GreenOnSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val GreenSecondaryContainerLightMediumContrast = Color(0xFF667157)
val GreenOnSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val GreenTertiaryLightMediumContrast = Color(0xFF083D3A)
val GreenOnTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val GreenTertiaryContainerLightMediumContrast = Color(0xFF477572)
val GreenOnTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val GreenErrorLightMediumContrast = Color(0xFF740006)
val GreenOnErrorLightMediumContrast = Color(0xFFFFFFFF)
val GreenErrorContainerLightMediumContrast = Color(0xFFCF2C27)
val GreenOnErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val GreenBackgroundLightMediumContrast = Color(0xFFF9FAEF)
val GreenOnBackgroundLightMediumContrast = Color(0xFF1A1C16)
val GreenSurfaceLightMediumContrast = Color(0xFFF9FAEF)
val GreenOnSurfaceLightMediumContrast = Color(0xFF0F120C)
val GreenSurfaceVariantLightMediumContrast = Color(0xFFE1E4D5)
val GreenOnSurfaceVariantLightMediumContrast = Color(0xFF34382D)
val GreenOutlineLightMediumContrast = Color(0xFF505449)
val GreenOutlineVariantLightMediumContrast = Color(0xFF6B6F62)
val GreenScrimLightMediumContrast = Color(0xFF000000)
val GreenInverseSurfaceLightMediumContrast = Color(0xFF2F312A)
val GreenInverseOnSurfaceLightMediumContrast = Color(0xFFF1F2E6)
val GreenInversePrimaryLightMediumContrast = Color(0xFFB1D18A)
val GreenSurfaceDimLightMediumContrast = Color(0xFFC6C7BD)
val GreenSurfaceBrightLightMediumContrast = Color(0xFFF9FAEF)
val GreenSurfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val GreenSurfaceContainerLowLightMediumContrast = Color(0xFFF3F4E9)
val GreenSurfaceContainerLightMediumContrast = Color(0xFFE8E9DE)
val GreenSurfaceContainerHighLightMediumContrast = Color(0xFFDCDED3)
val GreenSurfaceContainerHighestLightMediumContrast = Color(0xFFD1D3C8)

val GreenPrimaryLightHighContrast = Color(0xFF1C3200)
val GreenOnPrimaryLightHighContrast = Color(0xFFFFFFFF)
val GreenPrimaryContainerLightHighContrast = Color(0xFF375018)
val GreenOnPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val GreenSecondaryLightHighContrast = Color(0xFF262F1A)
val GreenOnSecondaryLightHighContrast = Color(0xFFFFFFFF)
val GreenSecondaryContainerLightHighContrast = Color(0xFF434C35)
val GreenOnSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val GreenTertiaryLightHighContrast = Color(0xFF003230)
val GreenOnTertiaryLightHighContrast = Color(0xFFFFFFFF)
val GreenTertiaryContainerLightHighContrast = Color(0xFF21504E)
val GreenOnTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val GreenErrorLightHighContrast = Color(0xFF600004)
val GreenOnErrorLightHighContrast = Color(0xFFFFFFFF)
val GreenErrorContainerLightHighContrast = Color(0xFF98000A)
val GreenOnErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val GreenBackgroundLightHighContrast = Color(0xFFF9FAEF)
val GreenOnBackgroundLightHighContrast = Color(0xFF1A1C16)
val GreenSurfaceLightHighContrast = Color(0xFFF9FAEF)
val GreenOnSurfaceLightHighContrast = Color(0xFF000000)
val GreenSurfaceVariantLightHighContrast = Color(0xFFE1E4D5)
val GreenOnSurfaceVariantLightHighContrast = Color(0xFF000000)
val GreenOutlineLightHighContrast = Color(0xFF2A2D24)
val GreenOutlineVariantLightHighContrast = Color(0xFF474B40)
val GreenScrimLightHighContrast = Color(0xFF000000)
val GreenInverseSurfaceLightHighContrast = Color(0xFF2F312A)
val GreenInverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val GreenInversePrimaryLightHighContrast = Color(0xFFB1D18A)
val GreenSurfaceDimLightHighContrast = Color(0xFFB8BAAF)
val GreenSurfaceBrightLightHighContrast = Color(0xFFF9FAEF)
val GreenSurfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val GreenSurfaceContainerLowLightHighContrast = Color(0xFFF1F2E6)
val GreenSurfaceContainerLightHighContrast = Color(0xFFE2E3D8)
val GreenSurfaceContainerHighLightHighContrast = Color(0xFFD4D5CA)
val GreenSurfaceContainerHighestLightHighContrast = Color(0xFFC6C7BD)

val GreenPrimaryDark = Color(0xFFB1D18A)
val GreenOnPrimaryDark = Color(0xFF1F3701)
val GreenPrimaryContainerDark = Color(0xFF354E16)
val GreenOnPrimaryContainerDark = Color(0xFFCDEDA3)
val GreenSecondaryDark = Color(0xFFBFCBAD)
val GreenOnSecondaryDark = Color(0xFF2A331E)
val GreenSecondaryContainerDark = Color(0xFF404A33)
val GreenOnSecondaryContainerDark = Color(0xFFDCE7C8)
val GreenTertiaryDark = Color(0xFFA0D0CB)
val GreenOnTertiaryDark = Color(0xFF003735)
val GreenTertiaryContainerDark = Color(0xFF1F4E4B)
val GreenOnTertiaryContainerDark = Color(0xFFBCECE7)
val GreenErrorDark = Color(0xFFFFB4AB)
val GreenOnErrorDark = Color(0xFF690005)
val GreenErrorContainerDark = Color(0xFF93000A)
val GreenOnErrorContainerDark = Color(0xFFFFDAD6)
val GreenBackgroundDark = Color(0xFF12140E)
val GreenOnBackgroundDark = Color(0xFFE2E3D8)
val GreenSurfaceDark = Color(0xFF12140E)
val GreenOnSurfaceDark = Color(0xFFE2E3D8)
val GreenSurfaceVariantDark = Color(0xFF44483D)
val GreenOnSurfaceVariantDark = Color(0xFFC5C8BA)
val GreenOutlineDark = Color(0xFF8F9285)
val GreenOutlineVariantDark = Color(0xFF44483D)
val GreenScrimDark = Color(0xFF000000)
val GreenInverseSurfaceDark = Color(0xFFE2E3D8)
val GreenInverseOnSurfaceDark = Color(0xFF2F312A)
val GreenInversePrimaryDark = Color(0xFF4C662B)
val GreenSurfaceDimDark = Color(0xFF12140E)
val GreenSurfaceBrightDark = Color(0xFF383A32)
val GreenSurfaceContainerLowestDark = Color(0xFF0C0F09)
val GreenSurfaceContainerLowDark = Color(0xFF1A1C16)
val GreenSurfaceContainerDark = Color(0xFF1E201A)
val GreenSurfaceContainerHighDark = Color(0xFF282B24)
val GreenSurfaceContainerHighestDark = Color(0xFF33362E)

val GreenPrimaryDarkMediumContrast = Color(0xFFC7E79E)
val GreenOnPrimaryDarkMediumContrast = Color(0xFF172B00)
val GreenPrimaryContainerDarkMediumContrast = Color(0xFF7D9A59)
val GreenOnPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val GreenSecondaryDarkMediumContrast = Color(0xFFD5E1C2)
val GreenOnSecondaryDarkMediumContrast = Color(0xFF1F2814)
val GreenSecondaryContainerDarkMediumContrast = Color(0xFF8A9579)
val GreenOnSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val GreenTertiaryDarkMediumContrast = Color(0xFFB5E6E1)
val GreenOnTertiaryDarkMediumContrast = Color(0xFF002B29)
val GreenTertiaryContainerDarkMediumContrast = Color(0xFF6B9995)
val GreenOnTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val GreenErrorDarkMediumContrast = Color(0xFFFFD2CC)
val GreenOnErrorDarkMediumContrast = Color(0xFF540003)
val GreenErrorContainerDarkMediumContrast = Color(0xFFFF5449)
val GreenOnErrorContainerDarkMediumContrast = Color(0xFF000000)
val GreenBackgroundDarkMediumContrast = Color(0xFF12140E)
val GreenOnBackgroundDarkMediumContrast = Color(0xFFE2E3D8)
val GreenSurfaceDarkMediumContrast = Color(0xFF12140E)
val GreenOnSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val GreenSurfaceVariantDarkMediumContrast = Color(0xFF44483D)
val GreenOnSurfaceVariantDarkMediumContrast = Color(0xFFDBDECF)
val GreenOutlineDarkMediumContrast = Color(0xFFB0B3A6)
val GreenOutlineVariantDarkMediumContrast = Color(0xFF8E9285)
val GreenScrimDarkMediumContrast = Color(0xFF000000)
val GreenInverseSurfaceDarkMediumContrast = Color(0xFFE2E3D8)
val GreenInverseOnSurfaceDarkMediumContrast = Color(0xFF282B24)
val GreenInversePrimaryDarkMediumContrast = Color(0xFF364F17)
val GreenSurfaceDimDarkMediumContrast = Color(0xFF12140E)
val GreenSurfaceBrightDarkMediumContrast = Color(0xFF43453D)
val GreenSurfaceContainerLowestDarkMediumContrast = Color(0xFF060804)
val GreenSurfaceContainerLowDarkMediumContrast = Color(0xFF1C1E18)
val GreenSurfaceContainerDarkMediumContrast = Color(0xFF262922)
val GreenSurfaceContainerHighDarkMediumContrast = Color(0xFF31342C)
val GreenSurfaceContainerHighestDarkMediumContrast = Color(0xFF3C3F37)

val GreenPrimaryDarkHighContrast = Color(0xFFDAFBB0)
val GreenOnPrimaryDarkHighContrast = Color(0xFF000000)
val GreenPrimaryContainerDarkHighContrast = Color(0xFFADCD86)
val GreenOnPrimaryContainerDarkHighContrast = Color(0xFF050E00)
val GreenSecondaryDarkHighContrast = Color(0xFFE9F4D5)
val GreenOnSecondaryDarkHighContrast = Color(0xFF000000)
val GreenSecondaryContainerDarkHighContrast = Color(0xFFBCC7A9)
val GreenOnSecondaryContainerDarkHighContrast = Color(0xFF060D01)
val GreenTertiaryDarkHighContrast = Color(0xFFC9F9F5)
val GreenOnTertiaryDarkHighContrast = Color(0xFF000000)
val GreenTertiaryContainerDarkHighContrast = Color(0xFF9CCCC7)
val GreenOnTertiaryContainerDarkHighContrast = Color(0xFF000E0D)
val GreenErrorDarkHighContrast = Color(0xFFFFECE9)
val GreenOnErrorDarkHighContrast = Color(0xFF000000)
val GreenErrorContainerDarkHighContrast = Color(0xFFFFAEA4)
val GreenOnErrorContainerDarkHighContrast = Color(0xFF220001)
val GreenBackgroundDarkHighContrast = Color(0xFF12140E)
val GreenOnBackgroundDarkHighContrast = Color(0xFFE2E3D8)
val GreenSurfaceDarkHighContrast = Color(0xFF12140E)
val GreenOnSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val GreenSurfaceVariantDarkHighContrast = Color(0xFF44483D)
val GreenOnSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val GreenOutlineDarkHighContrast = Color(0xFFEEF2E2)
val GreenOutlineVariantDarkHighContrast = Color(0xFFC1C4B6)
val GreenScrimDarkHighContrast = Color(0xFF000000)
val GreenInverseSurfaceDarkHighContrast = Color(0xFFE2E3D8)
val GreenInverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val GreenInversePrimaryDarkHighContrast = Color(0xFF364F17)
val GreenSurfaceDimDarkHighContrast = Color(0xFF12140E)
val GreenSurfaceBrightDarkHighContrast = Color(0xFF4F5149)
val GreenSurfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val GreenSurfaceContainerLowDarkHighContrast = Color(0xFF1E201A)
val GreenSurfaceContainerDarkHighContrast = Color(0xFF2F312A)
val GreenSurfaceContainerHighDarkHighContrast = Color(0xFF3A3C35)
val GreenSurfaceContainerHighestDarkHighContrast = Color(0xFF454840)

val GreenLightColorScheme = lightColorScheme(
    primary = GreenPrimaryLight,
    onPrimary = GreenOnPrimaryLight,
    primaryContainer = GreenPrimaryContainerLight,
    onPrimaryContainer = GreenOnPrimaryContainerLight,
    inversePrimary = GreenInversePrimaryLight,
    secondary = GreenSecondaryLight,
    onSecondary = GreenOnSecondaryLight,
    secondaryContainer = GreenSecondaryContainerLight,
    onSecondaryContainer = GreenOnSecondaryContainerLight,
    tertiary = GreenTertiaryLight,
    onTertiary = GreenOnTertiaryLight,
    tertiaryContainer = GreenTertiaryContainerLight,
    onTertiaryContainer = GreenOnTertiaryContainerLight,
    background = GreenBackgroundLight,
    onBackground = GreenOnBackgroundLight,
    surface = GreenSurfaceLight,
    onSurface = GreenOnSurfaceLight,
    surfaceVariant = GreenSurfaceVariantLight,
    onSurfaceVariant = GreenOnSurfaceVariantLight,
    surfaceTint = GreenPrimaryLight,
    inverseSurface = GreenInverseSurfaceLight,
    inverseOnSurface = GreenInverseOnSurfaceLight,
    error = GreenErrorLight,
    onError = GreenOnErrorLight,
    errorContainer = GreenErrorContainerLight,
    onErrorContainer = GreenOnErrorContainerLight,
    outline = GreenOutlineLight,
    outlineVariant = GreenOutlineVariantLight,
    scrim = GreenScrimLight,
    surfaceBright = GreenSurfaceBrightLight,
    surfaceContainer = GreenSurfaceContainerLight,
    surfaceContainerHigh = GreenSurfaceContainerHighLight,
    surfaceContainerHighest = GreenSurfaceContainerHighestLight,
    surfaceContainerLow = GreenSurfaceContainerLowLight,
    surfaceContainerLowest = GreenSurfaceContainerLowestLight,
    surfaceDim = GreenSurfaceDimLight
)

val GreenDarkColorScheme = lightColorScheme(
    primary = GreenPrimaryDark,
    onPrimary = GreenOnPrimaryDark,
    primaryContainer = GreenPrimaryContainerDark,
    onPrimaryContainer = GreenOnPrimaryContainerDark,
    inversePrimary = GreenInversePrimaryDark,
    secondary = GreenSecondaryDark,
    onSecondary = GreenOnSecondaryDark,
    secondaryContainer = GreenSecondaryContainerDark,
    onSecondaryContainer = GreenOnSecondaryContainerDark,
    tertiary = GreenTertiaryDark,
    onTertiary = GreenOnTertiaryDark,
    tertiaryContainer = GreenTertiaryContainerDark,
    onTertiaryContainer = GreenOnTertiaryContainerDark,
    background = GreenBackgroundDark,
    onBackground = GreenOnBackgroundDark,
    surface = GreenSurfaceDark,
    onSurface = GreenOnSurfaceDark,
    surfaceVariant = GreenSurfaceVariantDark,
    onSurfaceVariant = GreenOnSurfaceVariantDark,
    surfaceTint = GreenPrimaryDark,
    inverseSurface = GreenInverseSurfaceDark,
    inverseOnSurface = GreenInverseOnSurfaceDark,
    error = GreenErrorDark,
    onError = GreenOnErrorDark,
    errorContainer = GreenErrorContainerDark,
    onErrorContainer = GreenOnErrorContainerDark,
    outline = GreenOutlineDark,
    outlineVariant = GreenOutlineVariantDark,
    scrim = GreenScrimDark,
    surfaceBright = GreenSurfaceBrightDark,
    surfaceContainer = GreenSurfaceContainerDark,
    surfaceContainerHigh = GreenSurfaceContainerHighDark,
    surfaceContainerHighest = GreenSurfaceContainerHighestDark,
    surfaceContainerLow = GreenSurfaceContainerLowDark,
    surfaceContainerLowest = GreenSurfaceContainerLowestDark,
    surfaceDim = GreenSurfaceDimDark
)