package com.kaerushi.monetify.core.ui.theme.color

import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val RedPrimaryLight = Color(0xFF8F4C38)
val RedOnPrimaryLight = Color(0xFFFFFFFF)
val RedPrimaryContainerLight = Color(0xFFFFDBD1)
val RedOnPrimaryContainerLight = Color(0xFF723523)
val RedSecondaryLight = Color(0xFF77574E)
val RedOnSecondaryLight = Color(0xFFFFFFFF)
val RedSecondaryContainerLight = Color(0xFFFFDBD1)
val RedOnSecondaryContainerLight = Color(0xFF5D4037)
val RedTertiaryLight = Color(0xFF6C5D2F)
val RedOnTertiaryLight = Color(0xFFFFFFFF)
val RedTertiaryContainerLight = Color(0xFFF5E1A7)
val RedOnTertiaryContainerLight = Color(0xFF534619)
val RedErrorLight = Color(0xFFBA1A1A)
val RedOnErrorLight = Color(0xFFFFFFFF)
val RedErrorContainerLight = Color(0xFFFFDAD6)
val RedOnErrorContainerLight = Color(0xFF93000A)
val RedBackgroundLight = Color(0xFFFFF8F6)
val RedOnBackgroundLight = Color(0xFF231917)
val RedSurfaceLight = Color(0xFFFFF8F6)
val RedOnSurfaceLight = Color(0xFF231917)
val RedSurfaceVariantLight = Color(0xFFF5DED8)
val RedOnSurfaceVariantLight = Color(0xFF53433F)
val RedOutlineLight = Color(0xFF85736E)
val RedOutlineVariantLight = Color(0xFFD8C2BC)
val RedScrimLight = Color(0xFF000000)
val RedInverseSurfaceLight = Color(0xFF392E2B)
val RedInverseOnSurfaceLight = Color(0xFFFFEDE8)
val RedInversePrimaryLight = Color(0xFFFFB5A0)
val RedSurfaceDimLight = Color(0xFFE8D6D2)
val RedSurfaceBrightLight = Color(0xFFFFF8F6)
val RedSurfaceContainerLowestLight = Color(0xFFFFFFFF)
val RedSurfaceContainerLowLight = Color(0xFFFFF1ED)
val RedSurfaceContainerLight = Color(0xFFFCEAE5)
val RedSurfaceContainerHighLight = Color(0xFFF7E4E0)
val RedSurfaceContainerHighestLight = Color(0xFFF1DFDA)

val RedPrimaryLightMediumContrast = Color(0xFF5D2514)
val RedOnPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val RedPrimaryContainerLightMediumContrast = Color(0xFFA15A45)
val RedOnPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val RedSecondaryLightMediumContrast = Color(0xFF4B2F28)
val RedOnSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val RedSecondaryContainerLightMediumContrast = Color(0xFF87655C)
val RedOnSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val RedTertiaryLightMediumContrast = Color(0xFF41350A)
val RedOnTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val RedTertiaryContainerLightMediumContrast = Color(0xFF7B6C3C)
val RedOnTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val RedErrorLightMediumContrast = Color(0xFF740006)
val RedOnErrorLightMediumContrast = Color(0xFFFFFFFF)
val RedErrorContainerLightMediumContrast = Color(0xFFCF2C27)
val RedOnErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val RedBackgroundLightMediumContrast = Color(0xFFFFF8F6)
val RedOnBackgroundLightMediumContrast = Color(0xFF231917)
val RedSurfaceLightMediumContrast = Color(0xFFFFF8F6)
val RedOnSurfaceLightMediumContrast = Color(0xFF180F0D)
val RedSurfaceVariantLightMediumContrast = Color(0xFFF5DED8)
val RedOnSurfaceVariantLightMediumContrast = Color(0xFF41332F)
val RedOutlineLightMediumContrast = Color(0xFF5F4F4A)
val RedOutlineVariantLightMediumContrast = Color(0xFF7B6964)
val RedScrimLightMediumContrast = Color(0xFF000000)
val RedInverseSurfaceLightMediumContrast = Color(0xFF392E2B)
val RedInverseOnSurfaceLightMediumContrast = Color(0xFFFFEDE8)
val RedInversePrimaryLightMediumContrast = Color(0xFFFFB5A0)
val RedSurfaceDimLightMediumContrast = Color(0xFFD4C3BE)
val RedSurfaceBrightLightMediumContrast = Color(0xFFFFF8F6)
val RedSurfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val RedSurfaceContainerLowLightMediumContrast = Color(0xFFFFF1ED)
val RedSurfaceContainerLightMediumContrast = Color(0xFFF7E4E0)
val RedSurfaceContainerHighLightMediumContrast = Color(0xFFEBD9D4)
val RedSurfaceContainerHighestLightMediumContrast = Color(0xFFDFCEC9)

val RedPrimaryLightHighContrast = Color(0xFF501B0B)
val RedOnPrimaryLightHighContrast = Color(0xFFFFFFFF)
val RedPrimaryContainerLightHighContrast = Color(0xFF753725)
val RedOnPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val RedSecondaryLightHighContrast = Color(0xFF3F261E)
val RedOnSecondaryLightHighContrast = Color(0xFFFFFFFF)
val RedSecondaryContainerLightHighContrast = Color(0xFF60423A)
val RedOnSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val RedTertiaryLightHighContrast = Color(0xFF362B02)
val RedOnTertiaryLightHighContrast = Color(0xFFFFFFFF)
val RedTertiaryContainerLightHighContrast = Color(0xFF55481C)
val RedOnTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val RedErrorLightHighContrast = Color(0xFF600004)
val RedOnErrorLightHighContrast = Color(0xFFFFFFFF)
val RedErrorContainerLightHighContrast = Color(0xFF98000A)
val RedOnErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val RedBackgroundLightHighContrast = Color(0xFFFFF8F6)
val RedOnBackgroundLightHighContrast = Color(0xFF231917)
val RedSurfaceLightHighContrast = Color(0xFFFFF8F6)
val RedOnSurfaceLightHighContrast = Color(0xFF000000)
val RedSurfaceVariantLightHighContrast = Color(0xFFF5DED8)
val RedOnSurfaceVariantLightHighContrast = Color(0xFF000000)
val RedOutlineLightHighContrast = Color(0xFF372925)
val RedOutlineVariantLightHighContrast = Color(0xFF554641)
val RedScrimLightHighContrast = Color(0xFF000000)
val RedInverseSurfaceLightHighContrast = Color(0xFF392E2B)
val RedInverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val RedInversePrimaryLightHighContrast = Color(0xFFFFB5A0)
val RedSurfaceDimLightHighContrast = Color(0xFFC6B5B1)
val RedSurfaceBrightLightHighContrast = Color(0xFFFFF8F6)
val RedSurfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val RedSurfaceContainerLowLightHighContrast = Color(0xFFFFEDE8)
val RedSurfaceContainerLightHighContrast = Color(0xFFF1DFDA)
val RedSurfaceContainerHighLightHighContrast = Color(0xFFE2D1CC)
val RedSurfaceContainerHighestLightHighContrast = Color(0xFFD4C3BE)

val RedPrimaryDark = Color(0xFFFFB5A0)
val RedOnPrimaryDark = Color(0xFF561F0F)
val RedPrimaryContainerDark = Color(0xFF723523)
val RedOnPrimaryContainerDark = Color(0xFFFFDBD1)
val RedSecondaryDark = Color(0xFFE7BDB2)
val RedOnSecondaryDark = Color(0xFF442A22)
val RedSecondaryContainerDark = Color(0xFF5D4037)
val RedOnSecondaryContainerDark = Color(0xFFFFDBD1)
val RedTertiaryDark = Color(0xFFD8C58D)
val RedOnTertiaryDark = Color(0xFF3B2F05)
val RedTertiaryContainerDark = Color(0xFF534619)
val RedOnTertiaryContainerDark = Color(0xFFF5E1A7)
val RedErrorDark = Color(0xFFFFB4AB)
val RedOnErrorDark = Color(0xFF690005)
val RedErrorContainerDark = Color(0xFF93000A)
val RedOnErrorContainerDark = Color(0xFFFFDAD6)
val RedBackgroundDark = Color(0xFF1A110F)
val RedOnBackgroundDark = Color(0xFFF1DFDA)
val RedSurfaceDark = Color(0xFF1A110F)
val RedOnSurfaceDark = Color(0xFFF1DFDA)
val RedSurfaceVariantDark = Color(0xFF53433F)
val RedOnSurfaceVariantDark = Color(0xFFD8C2BC)
val RedOutlineDark = Color(0xFFA08C87)
val RedOutlineVariantDark = Color(0xFF53433F)
val RedScrimDark = Color(0xFF000000)
val RedInverseSurfaceDark = Color(0xFFF1DFDA)
val RedInverseOnSurfaceDark = Color(0xFF392E2B)
val RedInversePrimaryDark = Color(0xFF8F4C38)
val RedSurfaceDimDark = Color(0xFF1A110F)
val RedSurfaceBrightDark = Color(0xFF423734)
val RedSurfaceContainerLowestDark = Color(0xFF140C0A)
val RedSurfaceContainerLowDark = Color(0xFF231917)
val RedSurfaceContainerDark = Color(0xFF271D1B)
val RedSurfaceContainerHighDark = Color(0xFF322825)
val RedSurfaceContainerHighestDark = Color(0xFF3D322F)

val RedPrimaryDarkMediumContrast = Color(0xFFFFD2C6)
val RedOnPrimaryDarkMediumContrast = Color(0xFF481506)
val RedPrimaryContainerDarkMediumContrast = Color(0xFFCB7C65)
val RedOnPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val RedSecondaryDarkMediumContrast = Color(0xFFFED3C7)
val RedOnSecondaryDarkMediumContrast = Color(0xFF381F18)
val RedSecondaryContainerDarkMediumContrast = Color(0xFFAE887E)
val RedOnSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val RedTertiaryDarkMediumContrast = Color(0xFFEFDBA1)
val RedOnTertiaryDarkMediumContrast = Color(0xFF2F2500)
val RedTertiaryContainerDarkMediumContrast = Color(0xFFA0905C)
val RedOnTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val RedErrorDarkMediumContrast = Color(0xFFFFD2CC)
val RedOnErrorDarkMediumContrast = Color(0xFF540003)
val RedErrorContainerDarkMediumContrast = Color(0xFFFF5449)
val RedOnErrorContainerDarkMediumContrast = Color(0xFF000000)
val RedBackgroundDarkMediumContrast = Color(0xFF1A110F)
val RedOnBackgroundDarkMediumContrast = Color(0xFFF1DFDA)
val RedSurfaceDarkMediumContrast = Color(0xFF1A110F)
val RedOnSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val RedSurfaceVariantDarkMediumContrast = Color(0xFF53433F)
val RedOnSurfaceVariantDarkMediumContrast = Color(0xFFEED7D1)
val RedOutlineDarkMediumContrast = Color(0xFFC2ADA8)
val RedOutlineVariantDarkMediumContrast = Color(0xFFA08C87)
val RedScrimDarkMediumContrast = Color(0xFF000000)
val RedInverseSurfaceDarkMediumContrast = Color(0xFFF1DFDA)
val RedInverseOnSurfaceDarkMediumContrast = Color(0xFF322825)
val RedInversePrimaryDarkMediumContrast = Color(0xFF743624)
val RedSurfaceDimDarkMediumContrast = Color(0xFF1A110F)
val RedSurfaceBrightDarkMediumContrast = Color(0xFF4E423F)
val RedSurfaceContainerLowestDarkMediumContrast = Color(0xFF0D0604)
val RedSurfaceContainerLowDarkMediumContrast = Color(0xFF251B19)
val RedSurfaceContainerDarkMediumContrast = Color(0xFF302623)
val RedSurfaceContainerHighDarkMediumContrast = Color(0xFF3B302D)
val RedSurfaceContainerHighestDarkMediumContrast = Color(0xFF463B38)

val RedPrimaryDarkHighContrast = Color(0xFFFFECE7)
val RedOnPrimaryDarkHighContrast = Color(0xFF000000)
val RedPrimaryContainerDarkHighContrast = Color(0xFFFFAF98)
val RedOnPrimaryContainerDarkHighContrast = Color(0xFF1E0300)
val RedSecondaryDarkHighContrast = Color(0xFFFFECE7)
val RedOnSecondaryDarkHighContrast = Color(0xFF000000)
val RedSecondaryContainerDarkHighContrast = Color(0xFFE3B9AE)
val RedOnSecondaryContainerDarkHighContrast = Color(0xFF190603)
val RedTertiaryDarkHighContrast = Color(0xFFFFEFC4)
val RedOnTertiaryDarkHighContrast = Color(0xFF000000)
val RedTertiaryContainerDarkHighContrast = Color(0xFFD4C289)
val RedOnTertiaryContainerDarkHighContrast = Color(0xFF100B00)
val RedErrorDarkHighContrast = Color(0xFFFFECE9)
val RedOnErrorDarkHighContrast = Color(0xFF000000)
val RedErrorContainerDarkHighContrast = Color(0xFFFFAEA4)
val RedOnErrorContainerDarkHighContrast = Color(0xFF220001)
val RedBackgroundDarkHighContrast = Color(0xFF1A110F)
val RedOnBackgroundDarkHighContrast = Color(0xFFF1DFDA)
val RedSurfaceDarkHighContrast = Color(0xFF1A110F)
val RedOnSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val RedSurfaceVariantDarkHighContrast = Color(0xFF53433F)
val RedOnSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val RedOutlineDarkHighContrast = Color(0xFFFFECE7)
val RedOutlineVariantDarkHighContrast = Color(0xFFD4BEB8)
val RedScrimDarkHighContrast = Color(0xFF000000)
val RedInverseSurfaceDarkHighContrast = Color(0xFFF1DFDA)
val RedInverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val RedInversePrimaryDarkHighContrast = Color(0xFF743624)
val RedSurfaceDimDarkHighContrast = Color(0xFF1A110F)
val RedSurfaceBrightDarkHighContrast = Color(0xFF5A4D4A)
val RedSurfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val RedSurfaceContainerLowDarkHighContrast = Color(0xFF271D1B)
val RedSurfaceContainerDarkHighContrast = Color(0xFF392E2B)
val RedSurfaceContainerHighDarkHighContrast = Color(0xFF443936)
val RedSurfaceContainerHighestDarkHighContrast = Color(0xFF504441)

val RedLightColorScheme = lightColorScheme(
    primary = RedPrimaryLight,
    onPrimary = RedOnPrimaryLight,
    primaryContainer = RedPrimaryContainerLight,
    onPrimaryContainer = RedOnPrimaryContainerLight,
    inversePrimary = RedInversePrimaryLight,
    secondary = RedSecondaryLight,
    onSecondary = RedOnSecondaryLight,
    secondaryContainer = RedSecondaryContainerLight,
    onSecondaryContainer = RedOnSecondaryContainerLight,
    tertiary = RedTertiaryLight,
    onTertiary = RedOnTertiaryLight,
    tertiaryContainer = RedTertiaryContainerLight,
    onTertiaryContainer = RedOnTertiaryContainerLight,
    background = RedBackgroundLight,
    onBackground = RedOnBackgroundLight,
    surface = RedSurfaceLight,
    onSurface = RedOnSurfaceLight,
    surfaceVariant = RedSurfaceVariantLight,
    onSurfaceVariant = RedOnSurfaceVariantLight,
    surfaceTint = RedPrimaryLight,
    inverseSurface = RedInverseSurfaceLight,
    inverseOnSurface = RedInverseOnSurfaceLight,
    error = RedErrorLight,
    onError = RedOnErrorLight,
    errorContainer = RedErrorContainerLight,
    onErrorContainer = RedOnErrorContainerLight,
    outline = RedOutlineLight,
    outlineVariant = RedOutlineVariantLight,
    scrim = RedScrimLight,
    surfaceBright = RedSurfaceBrightLight,
    surfaceContainer = RedSurfaceContainerLight,
    surfaceContainerHigh = RedSurfaceContainerHighLight,
    surfaceContainerHighest = RedSurfaceContainerHighestLight,
    surfaceContainerLow = RedSurfaceContainerLowLight,
    surfaceContainerLowest = RedSurfaceContainerLowestLight,
    surfaceDim = RedSurfaceDimLight
)

val RedDarkColorScheme = lightColorScheme(
    primary = RedPrimaryDark,
    onPrimary = RedOnPrimaryDark,
    primaryContainer = RedPrimaryContainerDark,
    onPrimaryContainer = RedOnPrimaryContainerDark,
    inversePrimary = RedInversePrimaryDark,
    secondary = RedSecondaryDark,
    onSecondary = RedOnSecondaryDark,
    secondaryContainer = RedSecondaryContainerDark,
    onSecondaryContainer = RedOnSecondaryContainerDark,
    tertiary = RedTertiaryDark,
    onTertiary = RedOnTertiaryDark,
    tertiaryContainer = RedTertiaryContainerDark,
    onTertiaryContainer = RedOnTertiaryContainerDark,
    background = RedBackgroundDark,
    onBackground = RedOnBackgroundDark,
    surface = RedSurfaceDark,
    onSurface = RedOnSurfaceDark,
    surfaceVariant = RedSurfaceVariantDark,
    onSurfaceVariant = RedOnSurfaceVariantDark,
    surfaceTint = RedPrimaryDark,
    inverseSurface = RedInverseSurfaceDark,
    inverseOnSurface = RedInverseOnSurfaceDark,
    error = RedErrorDark,
    onError = RedOnErrorDark,
    errorContainer = RedErrorContainerDark,
    onErrorContainer = RedOnErrorContainerDark,
    outline = RedOutlineDark,
    outlineVariant = RedOutlineVariantDark,
    scrim = RedScrimDark,
    surfaceBright = RedSurfaceBrightDark,
    surfaceContainer = RedSurfaceContainerDark,
    surfaceContainerHigh = RedSurfaceContainerHighDark,
    surfaceContainerHighest = RedSurfaceContainerHighestDark,
    surfaceContainerLow = RedSurfaceContainerLowDark,
    surfaceContainerLowest = RedSurfaceContainerLowestDark,
    surfaceDim = RedSurfaceDimDark
)