package com.kaerushi.monetify.xposed.hooks.pinterest

import com.kaerushi.monetify.R

object IconPack {
    val duotoneDrawables: Map<String, Int> = mapOf(
        "ic_vr_home_gestalt" to R.drawable.duotone_home,
        "ic_vr_home_fill_gestalt" to R.drawable.duotone_home_fill,
        "ic_vr_search_gestalt" to R.drawable.duotone_search,
        "ic_vr_search_fill_gestalt" to R.drawable.duotone_search_fill,
        "ic_vr_magnifying_glass_sparkle_gestalt" to R.drawable.duotone_search_spark,
        "ic_vr_add_gestalt" to R.drawable.duotone_plus,
        "ic_avatar_group_plus_gestalt" to R.drawable.duotone_plus,
        "ic_image_sticker_plus" to R.drawable.duotone_plus,
        "ic_plus_create_nonpds" to R.drawable.duotone_plus,
        "ic_plus_create_small_nonpds" to R.drawable.duotone_plus,
        "ic_vr_speech_ellipsis_gestalt" to R.drawable.duotone_chat,
        "ic_vr_speech_ellipsis_fill_gestalt" to R.drawable.duotone_chat_fill,
        "ic_vr_speech_outline_gestalt" to R.drawable.duotone_chat,
        "ic_vr_camera_gestalt" to R.drawable.duotone_camera,
        "ic_vr_pin_gestalt" to R.drawable.duotone_pin_vert,
        "ic_vr_angled_pin_gestalt" to R.drawable.duotone_pin,
        "ic_vr_compact_angled_pin_gestalt" to R.drawable.duotone_pin_fill,
        "ic_vr_cancel_gestalt" to R.drawable.duotone_cross,
        "ic_vr_android_share_gestalt" to R.drawable.duotone_share_android,
        "ic_vr_download_gestalt" to R.drawable.duotone_download,
        "ic_vr_report_gestalt" to R.drawable.duotone_report,
        "ic_vr_heart_outline_gestalt" to R.drawable.duotone_heart,
        "ic_vr_ellipsis_gestalt" to R.drawable.duotone_more_24,
        "ic_vr_board_gestalt" to R.drawable.duotone_board,
        "ic_vr_collage_gestalt" to R.drawable.duotone_collage,
        "tab_bar_board_icon" to R.drawable.duotone_board,
        "ic_vr_arrow_back_gestalt" to R.drawable.duotone_arrow_back_compact,
        "ic_vr_directional_arrow_left_gestalt" to R.drawable.duotone_arrow_back,
        "ic_vr_eye_gestalt" to R.drawable.duotone_eye,
        "ic_vr_eye_hide_gestalt" to R.drawable.duotone_eye_disabled,
        "ic_vr_filter_gestalt" to R.drawable.duotone_option,
        "ic_vr_check_gestalt" to R.drawable.duotone_check,
        "ic_vr_check_circle_gestalt" to R.drawable.duotone_check_circle,
        "ic_vr_sound_gestalt" to R.drawable.duotone_volume_full,
        "ic_vr_mute_gestalt" to R.drawable.duotone_volume_zero,
        "ic_vr_maximize_gestalt" to R.drawable.duotone_expand,
        "ic_vr_captions_outline_gestalt" to R.drawable.duotone_captions,
        "ic_vr_captions_gestalt" to R.drawable.duotone_captions_fill,
        "ic_vr_instagram_gestalt" to R.drawable.duotone_instagram,
        "ic_vr_person_add_gestalt" to R.drawable.duotone_user_add,
        "ic_vr_person_gestalt" to R.drawable.duotone_user,
        "ic_vr_pencil_drawing_gestalt" to R.drawable.duotone_pencil_edit
    )
}